---
# file: tasks/feature_pack-installation.yml

- name: download feature pack
  include_tasks: 'fetch_feature_pack.yml'

- name: define temp_dir variable
  set_fact:
    temp_dir: '{{ tmpdir }}/{{ (data_store_file_downloaded.dest | basename | splitext)[0] }}'

- name: ensure temporary directory exists
  file:
    path: '{{ temp_dir }}'
    state: directory
    mode: 0644

- name: extract the contents of the feature pack zip file to a temporary folder
  unarchive:
    src: '{{ data_store_file_downloaded.dest }}'
    dest: '{{ temp_dir }}'
    remote_src: true
    mode: 0644

- name: copy jars to AEM install folder
  copy:
    src: '{{ temp_dir }}/jcr_root/libs/system/install/'
    dest: '{{ aem_install_dir }}/'
    remote_src: true
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0644
  become: true

# Pay attention to fact that config files can include configuration for node store services.
# For instance, S3 connector includes org.apache.jackrabbit.oak.plugins.document.DocumentNodeStoreService.config file
# with only option customBlobStore=B"true" inside.
# We must omit the replacement of this file if Mongo storage type is already configured at the previous stage
- name: copy config files to AEM install folder
  copy:
    src: '{{ temp_dir }}/jcr_root/libs/system/config/'
    dest: '{{ aem_install_dir }}/'
    force: no  # do not replace node store service config if exists. Must work in conjunction with mongo storage type
    remote_src: true
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    mode: 0644
  become: true
