---
# file: tasks/install.yml
- name: 'activating transport'
  include_tasks: 'fetch_{{ download_transport }}.yml'

- name: extract AEM jar file if crx-quickstart folder doesn't exist
  command: 'java -jar {{ aem_home }}/{{ cq_file_name }}.jar -unpack'
  args:
    creates: '{{ aem_home }}/crx-quickstart/bin'
    chdir: '{{ aem_home }}'
  become: true

- name: ensure that all permissions for home aem dir is correct
  file:
    path: '{{ aem_home }}/crx-quickstart'
    state: directory
    owner: '{{ aem_user }}'
    group: '{{ aem_user }}'
    recurse: true
    mode: 0644
  become: true

- name: ensure that subsys directory exists
  file:
    path: '/var/lock/subsys'
    state: directory
    recurse: true
    mode: 0644
  become: true

- name: find jarfile
  find:
    paths: '{{ aem_home }}/crx-quickstart/app/'
    patterns: '*.jar'
  register: jarfile

- name: creating file with jarfile
  copy:
    dest: '{{ aem_home }}/aem_jar_file'
    content: "JARFILE={{ jarfile['files'][0]['path'] | replace('{{ aem_home }}','') }}"
    mode: 0644
  become: true

#- name: debug
#  debug:
#    msg: "JARFILE={{ jarfile['files'][0]['path'] | replace('{{ aem_home }}','') }}"

- name: configure node store if needed
  include_tasks: configure_node_store.yml
  when: aem_storage_type == 'mongo'

- name: configure data stores if needed
  include_tasks: configure_data_store.yml
  when: aem_datastore_type | length > 0

- name: creating systemd script for AEM instance
  template:
    src: aem.service.j2
    dest: '/etc/systemd/system/{{ aem_service_name }}.service'
    owner: root
    group: root
    mode: 0644
  become: true

- name: start and enable aem service
  service:
    name: '{{ aem_service_name }}'
    enabled: true
    state: started
  notify:
  - firstload aem
  become: true

- meta: flush_handlers

- block:
  - name: change admin password
    aem_password:
      id: '{{ aem_admin_login }}'
      old_password: '{{ aem_admin_password }}'
      new_password: '{{ aem_new_admin_password }}'
      host: 'http://localhost'
      port: '{{ aem_instance_port }}'

  - name: set new password
    set_fact:
      aem_admin_password: '{{ aem_new_admin_password }}'
  when: aem_change_default_admin_password
